### ISSUE TITLE
ARM64 Build has old/wrong dnsdist version

### ISSUE THREAD

**Issue by simkin** [Seji64/SniDust#4] opened 2022-07-10 15:45 UTC
I run into an error, any ideas?

```
root@dns:~# docker run --platform=arm64 -d -e ALLOWED_CLIENTS="127.0.0.1, PUBLIC_ISP_IP" -e EXTERNAL_IP=PUBLIC_VPS_IP -p 443:443 -p 80:80 -p 53:5300/udp ghcr.io/seji64/snidust:main
Unable to find image 'ghcr.io/seji64/snidust:main' locally
main: Pulling from seji64/snidust
3b157c852f27: Pull complete
cfb57595ff3b: Pull complete
804328de888a: Pull complete
26291428536d: Pull complete
8c02c47c5ae0: Pull complete
7935da287b0b: Pull complete
4a0a6df502de: Pull complete
31557fadf023: Pull complete
8dcb500e3abb: Pull complete
7b7f2a869ba3: Pull complete
a738dc13db02: Pull complete
Digest: sha256:2eaad84c3e70b354626e2c993ddd03b791ce965c846a2e4d226d3b8ede0e100b
Status: Downloaded newer image for ghcr.io/seji64/snidust:main
1e8c4006536e600698bd69f71ffb77b2808b5f0cc3129abfcb5e5e730b5ebc4c

```
```
root@dns:~# docker ps -a
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                      PORTS     NAMES
1e8c4006536e   ghcr.io/seji64/snidust:main             "/usr/bin/tini -- /e…"   32 seconds ago   Exited (1) 10 seconds ago             musing_sutherland
```
```
root@dns:~# docker logs 1e8c4006536e
Dnsdist webserver password not set - generating one
Generated WebServer Password: Xqcvau6bgscg
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: StFaJtnlaM09WrfrrC1OWfgV0FuFHO9y
Starting DNSDist...
Starting sniproxy
[INFO] Using PUBLIC_VPS_IP - Point your DNS settings to this address
[SniDust] Loading Blocklist...
[SniDust] Adding domain myip.is to list
[SniDust] Adding domain ifconfig.co to list
[SniDust] Adding domain akadns.net to list
[SniDust] Adding domain akam.net to list
[SniDust] Adding domain akamai.com to list
[SniDust] Adding domain akamai.net to list
[SniDust] Adding domain akamaiedge.net to list
[SniDust] Adding domain akamaihd.net to list
[SniDust] Adding domain akamaistream.net to list
[SniDust] Adding domain akamaitech.net to list
[SniDust] Adding domain akamaitechnologies.com to list
[SniDust] Adding domain akamaitechnologies.fr to list
[SniDust] Adding domain akamaized.net to list
[SniDust] Adding domain edgekey.net to list
[SniDust] Adding domain edgesuite.net to list
[SniDust] Adding domain srip.net to list
[SniDust] Adding domain footprint.net to list
[SniDust] Adding domain level3.net to list
[SniDust] Adding domain llnwd.net to list
[SniDust] Adding domain edgecastcdn.net to list
[SniDust] Adding domain cloudfront.net to list
[SniDust] Adding domain zattoohds-a.akamaihd.net to list
[SniDust] Adding domain zathdslive-a.akamaihd.net to list
[SniDust] Adding domain zahs.tv to list
[SniDust] Adding domain zatsslive-a.akamaihd.net to list
[SniDust] Adding domain chromecast-receiver.zattoo.com to list
[SniDust] Adding domain box30030.wemfbox.ch to list
[SniDust] Adding domain zattoo.wemfbox.ch to list
[SniDust] Adding domain zatsslive-a.akamaihd.net to list
[SniDust] Adding domain netflix.com to list
[SniDust] Adding domain netflix.de to list
[SniDust] Adding domain nflximg.net to list
[SniDust] Adding domain nflximg.com to list
[SniDust] Adding domain nflxvideo.net to list
[SniDust] Adding domain netflix.net to list
[SniDust] Adding domain nflximg.net to list
[SniDust] Adding domain nflxvideo.net to list
[SniDust] Adding domain nflxso.net to list
[SniDust] Adding domain nflxext.com to list
[SniDust] Adding domain hulu.com to list
[SniDust] Adding domain huluim.com to list
[SniDust] Adding domain hbonow.com to list
[SniDust] Adding domain hbogo.com to list
[SniDust] Adding domain hbo.com to list
[SniDust] Adding domain amazon.com to list
[SniDust] Adding domain amazon.co.uk to list
[SniDust] Adding domain amazonvideo.com to list
[SniDust] Adding domain crackle.com to list
[SniDust] Adding domain pandora.com to list
[SniDust] Adding domain vudu.com to list
[SniDust] Adding domain blinkbox.com to list
[SniDust] Adding domain abc.com to list
[SniDust] Adding domain fox.com to list
[SniDust] Adding domain theplatform.com to list
[SniDust] Adding domain nbc.com to list
[SniDust] Adding domain nbcuni.com to list
[SniDust] Adding domain ip2location.com to list
[SniDust] Adding domain pbs.org to list
[SniDust] Adding domain warnerbros.com to list
[SniDust] Adding domain southpark.cc.com to list
[SniDust] Adding domain cbs.com to list
[SniDust] Adding domain brightcove.com to list
[SniDust] Adding domain cwtv.com to list
[SniDust] Adding domain spike.com to list
[SniDust] Adding domain go.com to list
[SniDust] Adding domain mtv.com to list
[SniDust] Adding domain mtvnservices.com to list
[SniDust] Adding domain playstation.net to list
[SniDust] Adding domain uplynk.com to list
[SniDust] Adding domain maxmind.com to list
[SniDust] Adding domain disney.com to list
[SniDust] Adding domain disneyjunior.com to list
[SniDust] Adding domain xboxlive.com to list
[SniDust] Adding domain lovefilm.com to list
[SniDust] Adding domain turner.com to list
[SniDust] Adding domain amctv.com to list
[SniDust] Adding domain sho.com to list
[SniDust] Adding domain mog.com to list
[SniDust] Adding domain wdtvlive.com to list
[SniDust] Adding domain beinsportsconnect.tv to list
[SniDust] Adding domain beinsportsconnect.net to list
[SniDust] Adding domain fig.bbc.co.uk to list
[SniDust] Adding domain open.live.bbc.co.uk to list
[SniDust] Adding domain bbc.co.uk to list
[SniDust] Adding domain crunchyroll.com to list
[SniDust] Adding domain omtrdc.net to list
[SniDust] Adding domain sling.com to list
[SniDust] Adding domain movetv.com to list
[SniDust] Adding domain optus.com.au to list
[SniDust] Adding domain optusnet.com.au to list
[SniDust] Adding domain wilmaa.com to list
[SniDust] Adding domain wilmaa.wemfbox.ch to list
[SniDust] Adding domain wilm-ssl.wemfbox.ch to list
[SniDust] Adding domain user.wilmaa.tvbackbone.com to list
[SniDust] Adding domain multiscreencache.tvbackbone.com to list
[SniDust] Adding domain teleboy.ch to list
[SniDust] Adding domain wilmaa.customers.cdn.iptv.ch to list
[SniDust] Adding domain teleboy.customers.cdn.iptv.ch to list
[SniDust] Adding domain cdn.iptv.ch to list
[SniDust] Adding domain srgssr.ch to list
[SniDust] Adding domain cdn.rts.ch to list
[SniDust] Adding domain srgsnitch.herokuapp.com to list
[SniDust] Adding domain srg.live.ott.irdeto.com to list
[SniDust] Adding domain molotov.tv to list
[SniDust] Complete!
Fatal Lua error: [string "chunk"]:9: attempt to call global 'setACLFromFile' (a nil value)
```

**Comment by Seji64** [comment] 2022-07-10 19:38
Please Open a Shell inside of the Container (`docker exec -it <mycontainer> bash`) and Look whats inside of /etc/dnsdist

**Comment by simkin** [comment] 2022-07-11 06:34
I am unable to open a shell as the container fails to start, but that dir only contains the allowedClients.acl file with two entries: 127.0.0.1, PUBLIC_ISP_IP

**Comment by Seji64** [comment] 2022-07-11 07:28
I probably fails cause PUBLIC_ISP_IP is Not a valid IP Adress. You can get your ip via https://icanhazip.com

**Comment by simkin** [comment] 2022-07-11 07:45
It has a valid public address and curl icanhazip.com is working fine. How to workaround the failure? Passing PUBLIC_ISP_IP as ENV variable?

**Comment by Seji64** [comment] 2022-07-11 07:47
`PUBLIC_ISP_IP `is just a **PLACEHOLDER** you have to replavce this with YOUR Public IP. Same goes for `PUBLIC_VPS_IP`

**Comment by simkin** [comment] 2022-07-11 07:48
Ah, I thought the docker script retrieved it at start :)
So I need to replace the string (with the actual ext IP) in the docker run command, right?

**Comment by Seji64** [comment] 2022-07-11 07:51
Correct. Maybe a better **example**:

Your ISP IP: 10.195.1.1
Your VPS IP (where SniDust ist runnig) : 200.255.1.1

The your docker command would be:

`docker run --platform=arm64 -d -e ALLOWED_CLIENTS="127.0.0.1, 10.195.1.1" -e EXTERNAL_IP=200.255.1.1 -p 443:443 -p 80:80 -p 53:5300/udp ghcr.io/seji64/snidust:main`

**Comment by simkin** [comment] 2022-07-11 07:54
Thank you! So PUBLIC_ISP_IP = whitelist to populate the allowedClients.acl file? 
(The file was created but I guess the string value could not be parsed as IP address)

Will test and close this issue in a moment, thanks for the explanations!

**Comment by Seji64** [comment] 2022-07-11 07:56
> Thank you! So PUBLIC_ISP_IP = whitelist to populate the allowedClients.acl file?

Correct - i implemented it like this so not other people can abuse your SniDust instance.

**Comment by Seji64** [comment] 2022-07-11 07:57
Sry - close it yourself if everything is working

**Comment by simkin** [comment] 2022-07-11 08:03
Now run into the next problem :) 

```
Dnsdist webserver password not set - generating one
Generated WebServer Password: jE82ArG6LoZV
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: 05eBLGiw07XAD9FDWQI8JSDrUjVIPLP4
sed: can't read /etc/dnsdist/dnsdist.conf: No such file or directory
Starting DNSDist...
Starting sniproxy
[INFO] Using x.x.x.x - Point your DNS settings to this address
Unable to read configuration from '/etc/dnsdist/dnsdist.conf'
Listening on 127.0.0.1:53
dnsdist 1.5.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, ::1/128, fc00::/7, fe80::/10
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
No downstream servers defined: all packets will get dropped
Error while retrieving the security update for version dnsdist-1.5.1-3.Debian: Unable to get a valid Security Status update
Not validating response for security status update, this is a non-release version.
```

**Comment by Seji64** [comment] 2022-07-11 08:18
I think the issue is you using the arm64 Image which seems to quite different from the x86_x64 version. Cause dnsdist should be version `1.7.2` and not `1.5.1-3`. It seems the PowerDNS Repo does provide an arm64 version.

I will have a look at it.

**Comment by simkin** [comment] 2022-07-11 08:21
Shall I move the new issue to its own ticket? Might be better for future traceability?

**Comment by Seji64** [comment] 2022-07-11 08:24
No its okay. The project is not THAT big ;-)

**Comment by Seji64** [comment] 2022-07-11 09:26
I swichted to alpine linux (there those up to date packages availible) - try it again pls

**Comment by simkin** [comment] 2022-07-11 10:03
```
root@dns:/opt/snidus# docker logs 928c2d2dde95
Dnsdist webserver password not set - generating one
Generated WebServer Password: HTBS67sgtiPg
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: 4Kc2lsD3kA58xXZ5K27XXhTKTktWkmt5
sed: can't read /etc/dnsdist/dnsdist.conf: No such file or directory
Starting DNSDist...
Starting sniproxy
[INFO] Using x.x.x.x - Point your DNS settings to this address
Unable to read configuration from '/etc/dnsdist/dnsdist.conf'
Listening on 127.0.0.1:53
dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, ::1/128, fc00::/7, fe80::/10
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
No downstream servers defined: all packets will get dropped
Polled security status of version 1.7.1 at startup, no known issues reported: OK
```

**Comment by Seji64** [comment] 2022-07-11 13:31
You are sure you using the lastest image? I had a bug in it - maybe your pull and my fix overlapped?

**Comment by simkin** [comment] 2022-07-11 13:39
```
Unable to find image 'ghcr.io/seji64/snidust:main' locally
main: Pulling from seji64/snidust
b3c136eddcbf: Pull complete
c6e3f4b8df18: Pull complete
97404bb3eac2: Pull complete
a1f41de415f1: Pull complete
7b8ac2bbf429: Pull complete
7570486acd54: Pull complete
9f5032c0e00f: Pull complete
dac263ecfde8: Pull complete
Digest: sha256:4cedfadb50ab9a22d7f226d9b4bfbc0e920a55201c0063addb6499b86a674d15
Status: Downloaded newer image for ghcr.io/seji64/snidust:main
1cadc9b6ddae063461e645d80f929d62f4ec091cfa2b657011bc8f216e2c810a
```
```
root@dns:/opt/snidus# docker logs 1cadc9b6ddae
Dnsdist webserver password not set - generating one
Generated WebServer Password: IcoOCd2oK3EA
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: QQu_xB9Lg0j6YZwh_uZ47qdyElbfGfn-
sed: can't read /etc/dnsdist/dnsdist.conf: No such file or directory
Starting DNSDist...
Starting sniproxy
[INFO] Using x.x.x.x - Point your DNS settings to this address
Unable to read configuration from '/etc/dnsdist/dnsdist.conf'
Listening on 127.0.0.1:53
dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, ::1/128, fc00::/7, fe80::/10
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
No downstream servers defined: all packets will get dropped
Polled security status of version 1.7.1 at startup, no known issues reported: OK
```
I can open a socket on ports 80 and 443. 8080 and 53 are not listening

What about:

- "sed: can't read /etc/dnsdist/dnsdist.conf: No such file or directory"
- "Unable to read configuration from '/etc/dnsdist/dnsdist.conf'"
- "No downstream servers defined: all packets will get dropped"

**Comment by Seji64** [comment] 2022-07-11 14:06
I hav sadly no arm64 device / VM here. But on a normal x86 docker installation all is working fine:

```
docker run -it -e ALLOWED_CLIENTS="127.0.0.1, 10.195.1.1" ghcr.io/seji64/snidust:main
Unable to find image 'ghcr.io/seji64/snidust:main' locally
main: Pulling from seji64/snidust
2408cc74d12b: Pull complete
a7f3d2e2c944: Pull complete
6e549789ba4e: Pull complete
22f28bccdc71: Pull complete
b4351e58e59f: Pull complete
cf22022f3b59: Pull complete
9f5032c0e00f: Pull complete
dac263ecfde8: Pull complete
Digest: sha256:4cedfadb50ab9a22d7f226d9b4bfbc0e920a55201c0063addb6499b86a674d15
Status: Downloaded newer image for ghcr.io/seji64/snidust:main
External IP not set - trying to get IP by myself
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    336      0 --:--:-- --:--:-- --:--:--   340
Dnsdist webserver password not set - generating one
Generated WebServer Password: -IdbmF5H_Ddz
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: DXGeSrqBpcqB96SzgspncK4KZkhpbUhO
Starting DNSDist...
Starting sniproxy
[INFO] Using 185.186.222.11 - Point your DNS settings to this address
[SniDust] Loading Blocklist...
[SniDust] Adding domain myip.is to list
[SniDust] Adding domain ifconfig.co to list
[SniDust] Adding domain akadns.net to list
[SniDust] Adding domain akam.net to list
[SniDust] Adding domain akamai.com to list
[SniDust] Adding domain akamai.net to list
[SniDust] Adding domain akamaiedge.net to list
[SniDust] Adding domain akamaihd.net to list
[SniDust] Adding domain akamaistream.net to list
[SniDust] Adding domain akamaitech.net to list
[SniDust] Adding domain akamaitechnologies.com to list
[SniDust] Adding domain akamaitechnologies.fr to list
[SniDust] Adding domain akamaized.net to list
[SniDust] Adding domain edgekey.net to list
[SniDust] Adding domain edgesuite.net to list
[SniDust] Adding domain srip.net to list
[SniDust] Adding domain footprint.net to list
[SniDust] Adding domain level3.net to list
[SniDust] Adding domain llnwd.net to list
[SniDust] Adding domain edgecastcdn.net to list
[SniDust] Adding domain cloudfront.net to list
[SniDust] Adding domain zattoohds-a.akamaihd.net to list
[SniDust] Adding domain zathdslive-a.akamaihd.net to list
[SniDust] Adding domain zahs.tv to list
[SniDust] Adding domain zatsslive-a.akamaihd.net to list
[SniDust] Adding domain chromecast-receiver.zattoo.com to list
[SniDust] Adding domain box30030.wemfbox.ch to list
[SniDust] Adding domain zattoo.wemfbox.ch to list
[SniDust] Adding domain zatsslive-a.akamaihd.net to list
[SniDust] Adding domain netflix.com to list
[SniDust] Adding domain netflix.de to list
[SniDust] Adding domain nflximg.net to list
[SniDust] Adding domain nflximg.com to list
[SniDust] Adding domain nflxvideo.net to list
[SniDust] Adding domain netflix.net to list
[SniDust] Adding domain nflximg.net to list
[SniDust] Adding domain nflxvideo.net to list
[SniDust] Adding domain nflxso.net to list
[SniDust] Adding domain nflxext.com to list
[SniDust] Adding domain hulu.com to list
[SniDust] Adding domain huluim.com to list
[SniDust] Adding domain hbonow.com to list
[SniDust] Adding domain hbogo.com to list
[SniDust] Adding domain hbo.com to list
[SniDust] Adding domain amazon.com to list
[SniDust] Adding domain amazon.co.uk to list
[SniDust] Adding domain amazonvideo.com to list
[SniDust] Adding domain crackle.com to list
[SniDust] Adding domain pandora.com to list
[SniDust] Adding domain vudu.com to list
[SniDust] Adding domain blinkbox.com to list
[SniDust] Adding domain abc.com to list
[SniDust] Adding domain fox.com to list
[SniDust] Adding domain theplatform.com to list
[SniDust] Adding domain nbc.com to list
[SniDust] Adding domain nbcuni.com to list
[SniDust] Adding domain ip2location.com to list
[SniDust] Adding domain pbs.org to list
[SniDust] Adding domain warnerbros.com to list
[SniDust] Adding domain southpark.cc.com to list
[SniDust] Adding domain cbs.com to list
[SniDust] Adding domain brightcove.com to list
[SniDust] Adding domain cwtv.com to list
[SniDust] Adding domain spike.com to list
[SniDust] Adding domain go.com to list
[SniDust] Adding domain mtv.com to list
[SniDust] Adding domain mtvnservices.com to list
[SniDust] Adding domain playstation.net to list
[SniDust] Adding domain uplynk.com to list
[SniDust] Adding domain maxmind.com to list
[SniDust] Adding domain disney.com to list
[SniDust] Adding domain disneyjunior.com to list
[SniDust] Adding domain xboxlive.com to list
[SniDust] Adding domain lovefilm.com to list
[SniDust] Adding domain turner.com to list
[SniDust] Adding domain amctv.com to list
[SniDust] Adding domain sho.com to list
[SniDust] Adding domain mog.com to list
[SniDust] Adding domain wdtvlive.com to list
[SniDust] Adding domain beinsportsconnect.tv to list
[SniDust] Adding domain beinsportsconnect.net to list
[SniDust] Adding domain fig.bbc.co.uk to list
[SniDust] Adding domain open.live.bbc.co.uk to list
[SniDust] Adding domain bbc.co.uk to list
[SniDust] Adding domain crunchyroll.com to list
[SniDust] Adding domain omtrdc.net to list
[SniDust] Adding domain sling.com to list
[SniDust] Adding domain movetv.com to list
[SniDust] Adding domain optus.com.au to list
[SniDust] Adding domain optusnet.com.au to list
[SniDust] Adding domain wilmaa.com to list
[SniDust] Adding domain wilmaa.wemfbox.ch to list
[SniDust] Adding domain wilm-ssl.wemfbox.ch to list
[SniDust] Adding domain user.wilmaa.tvbackbone.com to list
[SniDust] Adding domain multiscreencache.tvbackbone.com to list
[SniDust] Adding domain teleboy.ch to list
[SniDust] Adding domain wilmaa.customers.cdn.iptv.ch to list
[SniDust] Adding domain teleboy.customers.cdn.iptv.ch to list
[SniDust] Adding domain cdn.iptv.ch to list
[SniDust] Adding domain srgssr.ch to list
[SniDust] Adding domain cdn.rts.ch to list
[SniDust] Adding domain srgsnitch.herokuapp.com to list
[SniDust] Adding domain srg.live.ott.irdeto.com to list
[SniDust] Adding domain molotov.tv to list
[SniDust] Complete!
Added downstream server 1.1.1.1:53
Added downstream server 1.0.0.1:53
Listening on 0.0.0.0:5300
dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: 10.195.1.1/32, 127.0.0.1/32
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
Webserver launched on 127.0.0.1:8083
Marking downstream 1.1.1.1:53 as 'up'
Marking downstream 1.0.0.1:53 as 'up'
Polled security status of version 1.7.1 at startup, no known issues reported: OK
```
I have absolutely no clue why the amr64 Image should behave completely different. On the Build Log you can also see the files are getting copied to `/etc/dnsdist:`

```
....
#24 [linux/arm64 3/8] COPY configs/dnsdist/dnsdist.conf /etc/dnsdist/dnsdist.conf
#24 DONE 0.0s
#25 [linux/arm/v7 7/8] COPY entrypoint.sh /entrypoint.sh
#25 DONE 0.0s
#26 [linux/arm64 4/8] COPY configs/dnsdist/conf.d/SniDust.conf /etc/dnsdist/conf.d/SniDust.conf
#26 DONE 0.0s
....
```
So if the directory does not exist here should be an error while building the docker image.

TL:DR;
The problem is `/etc/dnsdist/dnsdist.conf` does not exist. So dnsdist has no config at all - so no listerning on port 53 and so on.

**Comment by simkin** [comment] 2022-07-11 17:38
Not yet :(

```
Unable to find image 'ghcr.io/seji64/snidust:main' locally
main: Pulling from seji64/snidust
b3c136eddcbf: Pull complete
4eb475bad0d5: Pull complete
0ae4a209a7f0: Pull complete
a167320ef0fc: Pull complete
94d9e0767463: Pull complete
c365d14335b4: Pull complete
e5995fbde489: Pull complete
c837c8b0dc30: Pull complete
6f896dee3dfa: Pull complete
b1ce0263aebf: Pull complete
Digest: sha256:3c26108cf4fd694d72dd76ec64921a6a2015b47e66cbba79f247c5ef9a542abd
Status: Downloaded newer image for ghcr.io/seji64/snidust:main
2a313e6867c378dcb2b9739933d1c5aa20ec4d6846fa6684757db141c7aa9996
```
```
root@dns:/mnt/data/cloudflare-ddns# docker logs 2a313e6867c3
Dnsdist webserver password not set - generating one
Generated WebServer Password: nnfXp6OTrjA-
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: H_CRHRAsu0qIJfGQTwZgpOEV07suQcyi
sed: can't read /etc/dnsdist/dnsdist.conf: No such file or directory
Starting DNSDist...
Starting sniproxy
[INFO] Using x.x.x.x - Point your DNS settings to this address
Unable to read configuration from '/etc/dnsdist/dnsdist.conf'
Listening on 127.0.0.1:53
dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, ::1/128, fc00::/7, fe80::/10
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
No downstream servers defined: all packets will get dropped
Polled security status of version 1.7.1 at startup, no known issues reported: OK
```

**Comment by Seji64** [comment] 2022-07-11 17:44
Okay, last try: build the image yourself:

```
git clone https://github.com/Seji64/SniDust/
cd SniDust
docker build . -t smkin/testdust
docker run -it -e ALLOWED_CLIENTS="127.0.0.1, 10.195.1.1" smkin/testdust
```

**Comment by simkin** [comment] 2022-07-11 17:50
Works :) 

Guess I was not pulling your very latest image? Was it tagged differently?

```
root@dns:/opt/SniDust# docker run -it -e ALLOWED_CLIENTS="127.0.0.1, x.x.x.x" smkin/testdust
External IP not set - trying to get IP by myself
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0    196      0 --:--:-- --:--:-- --:--:--   200
Dnsdist webserver password not set - generating one
Generated WebServer Password: R7SDaXU-Srd5
Dnsdist webserver api key not set - generating one
Generated WebServer API Key: IacQ7BUMdQ27dsbMZfk4FFHPWg_yRylx
Starting DNSDist...
Starting sniproxy
[INFO] Using 62.195.180.6 - Point your DNS settings to this address
[SniDust] Loading Blocklist...
[SniDust] Adding domain myip.is to list
[SniDust] Adding domain ifconfig.co to list
[SniDust] Adding domain akadns.net to list
[SniDust] Adding domain akam.net to list
[SniDust] Adding domain akamai.com to list
[SniDust] Adding domain akamai.net to list
[SniDust] Adding domain akamaiedge.net to list
[SniDust] Adding domain akamaihd.net to list
[SniDust] Adding domain akamaistream.net to list
[SniDust] Adding domain akamaitech.net to list
[SniDust] Adding domain akamaitechnologies.com to list
[SniDust] Adding domain akamaitechnologies.fr to list
[SniDust] Adding domain akamaized.net to list
[SniDust] Adding domain edgekey.net to list
[SniDust] Adding domain edgesuite.net to list
[SniDust] Adding domain srip.net to list
[SniDust] Adding domain footprint.net to list
[SniDust] Adding domain level3.net to list
[SniDust] Adding domain llnwd.net to list
[SniDust] Adding domain edgecastcdn.net to list
[SniDust] Adding domain cloudfront.net to list
[SniDust] Adding domain zattoohds-a.akamaihd.net to list
[SniDust] Adding domain zathdslive-a.akamaihd.net to list
[SniDust] Adding domain zahs.tv to list
[SniDust] Adding domain zatsslive-a.akamaihd.net to list
[SniDust] Adding domain chromecast-receiver.zattoo.com to list
[SniDust] Adding domain box30030.wemfbox.ch to list
[SniDust] Adding domain zattoo.wemfbox.ch to list
[SniDust] Adding domain zatsslive-a.akamaihd.net to list
[SniDust] Adding domain netflix.com to list
[SniDust] Adding domain netflix.de to list
[SniDust] Adding domain nflximg.net to list
[SniDust] Adding domain nflximg.com to list
[SniDust] Adding domain nflxvideo.net to list
[SniDust] Adding domain netflix.net to list
[SniDust] Adding domain nflximg.net to list
[SniDust] Adding domain nflxvideo.net to list
[SniDust] Adding domain nflxso.net to list
[SniDust] Adding domain nflxext.com to list
[SniDust] Adding domain hulu.com to list
[SniDust] Adding domain huluim.com to list
[SniDust] Adding domain hbonow.com to list
[SniDust] Adding domain hbogo.com to list
[SniDust] Adding domain hbo.com to list
[SniDust] Adding domain amazon.com to list
[SniDust] Adding domain amazon.co.uk to list
[SniDust] Adding domain amazonvideo.com to list
[SniDust] Adding domain crackle.com to list
[SniDust] Adding domain pandora.com to list
[SniDust] Adding domain vudu.com to list
[SniDust] Adding domain blinkbox.com to list
[SniDust] Adding domain abc.com to list
[SniDust] Adding domain fox.com to list
[SniDust] Adding domain theplatform.com to list
[SniDust] Adding domain nbc.com to list
[SniDust] Adding domain nbcuni.com to list
[SniDust] Adding domain ip2location.com to list
[SniDust] Adding domain pbs.org to list
[SniDust] Adding domain warnerbros.com to list
[SniDust] Adding domain southpark.cc.com to list
[SniDust] Adding domain cbs.com to list
[SniDust] Adding domain brightcove.com to list
[SniDust] Adding domain cwtv.com to list
[SniDust] Adding domain spike.com to list
[SniDust] Adding domain go.com to list
[SniDust] Adding domain mtv.com to list
[SniDust] Adding domain mtvnservices.com to list
[SniDust] Adding domain playstation.net to list
[SniDust] Adding domain uplynk.com to list
[SniDust] Adding domain maxmind.com to list
[SniDust] Adding domain disney.com to list
[SniDust] Adding domain disneyjunior.com to list
[SniDust] Adding domain xboxlive.com to list
[SniDust] Adding domain lovefilm.com to list
[SniDust] Adding domain turner.com to list
[SniDust] Adding domain amctv.com to list
[SniDust] Adding domain sho.com to list
[SniDust] Adding domain mog.com to list
[SniDust] Adding domain wdtvlive.com to list
[SniDust] Adding domain beinsportsconnect.tv to list
[SniDust] Adding domain beinsportsconnect.net to list
[SniDust] Adding domain fig.bbc.co.uk to list
[SniDust] Adding domain open.live.bbc.co.uk to list
[SniDust] Adding domain bbc.co.uk to list
[SniDust] Adding domain crunchyroll.com to list
[SniDust] Adding domain omtrdc.net to list
[SniDust] Adding domain sling.com to list
[SniDust] Adding domain movetv.com to list
[SniDust] Adding domain optus.com.au to list
[SniDust] Adding domain optusnet.com.au to list
[SniDust] Adding domain wilmaa.com to list
[SniDust] Adding domain wilmaa.wemfbox.ch to list
[SniDust] Adding domain wilm-ssl.wemfbox.ch to list
[SniDust] Adding domain user.wilmaa.tvbackbone.com to list
[SniDust] Adding domain multiscreencache.tvbackbone.com to list
[SniDust] Adding domain teleboy.ch to list
[SniDust] Adding domain wilmaa.customers.cdn.iptv.ch to list
[SniDust] Adding domain teleboy.customers.cdn.iptv.ch to list
[SniDust] Adding domain cdn.iptv.ch to list
[SniDust] Adding domain srgssr.ch to list
[SniDust] Adding domain cdn.rts.ch to list
[SniDust] Adding domain srgsnitch.herokuapp.com to list
[SniDust] Adding domain srg.live.ott.irdeto.com to list
[SniDust] Adding domain molotov.tv to list
[SniDust] Complete!
Added downstream server 1.1.1.1:53
Added downstream server 1.0.0.1:53
Listening on 0.0.0.0:5300
dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: x.x.x.x, 127.0.0.1/32
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
Webserver launched on 127.0.0.1:8083
Marking downstream 1.0.0.1:53 as 'up'
Marking downstream 1.1.1.1:53 as 'up'
Polled security status of version 1.7.1 at startup, no known issues reported: OK
```

**Comment by Seji64** [comment] 2022-07-11 18:39
Nice, glad it works. The Tag didn‘t change. From the log Output you provided , the Image Digest was matching with those from github 🤷‍♂️

**Closed** 2022-07-12 16:01 UTC
Labels: good first issue
